name: Homes
version: @version@
main: com.github.m4kvn.spigot.homes.Main
api-version: @api-version@
commands:
  homes:
    description: This is Homes command.
    usage: /<command>
    aliases: ['home']