name: Playground
version: @version@
main: com.github.m4kvn.spigot.playground.Main
api-version: @api-version@
commands:
  playground:
    description: This is Playground command.
    usage: /<command>
    aliases:
      - pg
